const htmlmin = require('html-minifier-terser');
const isProd = process.env.ELEVENTY_ENV === 'production';

module.exports = (eleventyConfig) => {
  eleventyConfig.addTransform('html-minify', (content, outputPath) => {
    if (outputPath && outputPath.endsWith('.html') && isProd) {
      return htmlmin.minify(content, {
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        decodeEntities: true,
        includeAutoGeneratedTags: false,
        removeComments: true,
        useShortDoctype: true,
      });
    }

    return content;
  });
};
