backend: # Set up your backend
  name: github
  repo: mhaack/mh-site

local_backend: true

publish_mode: editorial_workflow
media_folder: content/images
public_folder: /images

collections:
  - name: "posts"
    create: true
    folder: "content/posts"
    label_singular: "Post"
    label: "Posts"
    media_folder: "/content/images/"
    public_folder: "/img"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sort: "date:desc"
    summary: "{{title}} ({{date}})"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Category"
        name: "category"
        widget: "select"
        default: ["project"]
        options: ["project", "work"]
      - label: "Tags"
        name: "tags"
        widget: "relation"
        collection: "tags"
        value_field: "name"
        search_fields: ["name"]
        multiple: true
      - label: "Hero"
        name: "images"
        widget: "object"
        fields:
          - label: "Feature"
            name: "feature"
            widget: "image"
          - label: "Feature Height"
            name: "height"
            widget: "select"
            options: ["h-64", "h-96", "h-128"]
            required: false
      - label: "Excerpt"
        name: "description"
        widget: "text"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "Slug"
        name: "permalink"
        widget: "string"
        required: false

  - name: "pages"
    label: "Seiten"
    files:
      - name: "home"
        label: "Homepage"
        file: "content/index.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Image", name: "image", widget: "string" }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "about"
        label: "About Me"
        file: "content/about.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "string" }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - name: "datasecurity"
        label: "Datenschutz"
        file: "content/datenschutz.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "No Index", name: "ignore", widget: "boolean", default: false }
          - { label: "Body", name: "body", widget: "markdown" }

      - name: "imprint"
        label: "Impressum"
        file: "content/impressum.md"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "No Index", name: "ignore", widget: "boolean", default: false }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "settings"
    label: "Settings"
    files:
      - name: "site"
        label: "Site settings"
        delete: false
        editor:
          preview: false
        file: "src/_data/site.json"
        fields:
          - label: "Site name"
            name: "name"
            widget: "string"
          - label: "Site meta description"
            name: "description"
            widget: "string"
          - label: "Site Language"
            name: "language"
            widget: "string"
          - label: "Author"
            name: "author"
            widget: "object"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "E-Mail"
                name: "email"
                widget: "string"
              - label: "Twitter"
                name: "twitterHandle"
                widget: "string"
          - label: "Default Social Image"
            name: "defaultSocialImage"
            widget: "string"
          - label: "Header Links"
            name: "headerLinks"
            widget: "list"
            summary: "{{fields.text}}"
            fields:
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Url"
                name: "url"
                widget: "string"
              - label: "External Link"
                name: "external"
                widget: "boolean"
          - label: "Social Links"
            name: "socialLinks"
            widget: "list"
            summary: "{{fields.text}}"
            fields:
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Url"
                name: "url"
                widget: "string"
              - label: "Icon"
                name: "icon"
                widget: "string"
              - label: "External Link"
                name: "external"
                widget: "boolean"
          - label: "Footer Links"
            name: "footerLinks"
            widget: "list"
            summary: "{{fields.text}}"
            fields:
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Url"
                name: "url"
                widget: "string"
              - label: "Icon"
                name: "icon"
                widget: "string"
              - label: "External Link"
                name: "external"
                widget: "boolean"
          - label: "Footer Attribution"
            name: "footerAttribution"
            widget: "string"

  - name: "tags"
    label: "Tags"
    label_singular: "Tag"
    folder: "content/tags"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    fields:
      - { label: "Tag Name", name: "name", widget: string }
