backend:
  name: github
  repo: mhaack/mh-site
  branch: main
local_backend: true

publish_mode: editorial_workflow
media_folder: src/assets/images
public_folder: /assets/images

collections:
  - name: posts
    create: true
    folder: src/posts
    label_singular: Post
    label: Posts
    media_folder: /src/assets/images/
    public_folder: /assets/images
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sort: date:desc
    summary: "{{title}} ({{date}})"
    fields:
      - label: Title
        name: title
        widget: string
        pattern:
          - ^.{50,80}$
          - Must be between 50 and 80 characters
        required: true
      - label: Description
        name: description
        widget: text
        pattern:
          - ^.{50,160}$
          - Must be between 50 and 200 characters
        required: true
      - label: Category
        name: category
        widget: select
        default:
          - project
        options:
          - project
          - work
        required: true
      - label: Tags
        name: tags
        widget: relation
        collection: tags
        value_field: name
        search_fields:
          - name
        multiple: true
      - label: Hero
        name: images
        widget: object
        fields:
          - label: Feature
            name: feature
            widget: image
          - label: Feature Height
            name: height
            widget: select
            required: false
            options:
              - h-64
              - h-96
              - h-128
      - label: SEO (optional)
        name: seo
        widget: object
        required: false
        fields:
          - label: Title
            name: title
            widget: string
            required: false
            pattern:
              - ^.{50,60}$
              - Must be between 50 and 60 characters
          - label: Description
            name: description
            required: false
            pattern:
              - ^.{50,160}$
              - Must be between 50 and 160 characters
            widget: text
      - label: Body
        name: body
        widget: markdown
      - label: Publish Date
        name: date
        widget: datetime
        format: YYYY-MM-DD
        dateFormat: YYYY-MM-DD
        timeFormat: false
      - label: Slug
        name: permalink
        widget: string
        required: false
  - name: pages
    label: Seiten
    files:
      - name: home
        label: Homepage
        file: src/pages/index.md
        fields:
          - label: Titel
            name: title
            widget: string
          - label: Description
            name: description
            widget: string
          - label: Image
            name: image
            widget: string
          - label: Layout
            name: layout
            widget: string
          - label: Body
            name: body
            widget: markdown
      - name: about
        label: About Me
        file: src/page/about.md
        fields:
          - label: Titel
            name: title
            widget: string
          - label: Image
            name: image
            widget: string
          - label: Layout
            name: layout
            widget: string
          - label: Body
            name: body
            widget: markdown
      - name: datasecurity
        label: Datenschutz
        file: src/page/datenschutz.md
        fields:
          - label: Titel
            name: title
            widget: string
          - label: Layout
            name: layout
            widget: string
          - label: No Index
            name: ignore
            widget: boolean
            default: false
          - label: Body
            name: body
            widget: markdown
      - name: imprint
        label: Impressum
        file: src/pages/impressum.md
        fields:
          - label: Titel
            name: title
            widget: string
          - label: Layout
            name: layout
            widget: string
          - label: No Index
            name: ignore
            widget: boolean
            default: false
          - label: Body
            name: body
            widget: markdown
  - name: settings
    label: Settings
    files:
      - name: site
        label: Site settings
        delete: false
        editor:
          preview: false
        file: src/_data/site.json
        fields:
          - label: Site name
            name: name
            widget: string
          - label: Site meta description
            name: description
            widget: string
          - label: Site Language
            name: language
            widget: string
          - label: Author
            name: author
            widget: object
            fields:
              - label: Name
                name: name
                widget: string
              - label: E-Mail
                name: email
                widget: string
              - label: Twitter
                name: twitterHandle
                widget: string
          - label: Default Social Image
            name: defaultSocialImage
            widget: string
          - label: Header Links
            name: headerLinks
            widget: list
            summary: "{{fields.text}}"
            fields:
              - label: Text
                name: text
                widget: string
              - label: Url
                name: url
                widget: string
              - label: External Link
                name: external
                widget: boolean
          - label: Social Links
            name: socialLinks
            widget: list
            summary: "{{fields.text}}"
            fields:
              - label: Text
                name: text
                widget: string
              - label: Url
                name: url
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: External Link
                name: external
                widget: boolean
          - label: Footer Links
            name: footerLinks
            widget: list
            summary: "{{fields.text}}"
            fields:
              - label: Text
                name: text
                widget: string
              - label: Url
                name: url
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: External Link
                name: external
                widget: boolean
          - label: Footer Attribution
            name: footerAttribution
            widget: string
  - name: tags
    label: Tags
    label_singular: Tag
    folder: admin/tags
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - label: Tag Name
        name: name
        widget: string
