name: Weekly Netlify Build

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    name: Daily Netlify Build
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify build hook
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}